version: 2

sources:
  - name: demo
    database: databricksdbt
    schema: jaffle_shop
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments
      - name: raw_notes

models:
  - name: stg_customers
    config:
      tags: ['stg']
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null

  - name: stg_orders
    config:
      tags: ['stg']
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              arguments:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    config:
      tags: ['stg']
    columns:
      - name: payment_id
        data_tests:
          - unique
          - not_null
      - name: payment_method
        data_tests:
          - accepted_values:
              arguments:
                values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
